### PR TITLE
Use electron spell checker

### PR DESCRIPTION
**Pull request by roggenbrot**
#26

### CODE REVIEW

**Comment by eNkru** [comment]
This solution is much better. Thanks for the contribution 👍

**Comment by sspade1** [comment]
Is there a way to have a local spell check different from english when composing a message, like outlook.com in any browser ?
I run Freelook in MX linux, a debian-based linux distro. I tried to copy the fr-FR.dic file from the hunspell-fr package in ~/config/Freelook/dictionnaries folder, but french language is still not activated when I right-click on a red-underlined french word. It could be activated through the right-click or a setting file.
Any idea ?
Regards

**Comment by sspade1** [comment]
I realised that Outlook.com in Brave browser (for some reason, not in some others) uses the Microsoft spell check:
https://www.microsoft.com/en-us/microsoft-365/microsoft-editor-options
This one is quite powerful, because it does a lexical and syntaxic check, according to the language setting of the account (I have not found the way to switch to another language yet).
My question is: Is there a way to use the same service in Freelook ?

**Comment by roggenbrot** [comment]
> I realised that Outlook.com in Brave browser (for some reason, not in some others) uses the Microsoft spell check:

This has to do with the agent string. If agent string is set to Chrome, freelook with automatically use the Microsoft spell checker

```
  win.webContents.setUserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3831.6 Safari/537.36");
```

**Comment by roggenbrot** [comment]
I'm also working on i18n improvements at the moment. Part of this is also setting custom dictionaries, custom spell checker languages

**Comment by sspade1** [comment]
>   win.webContents.setUserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3831.6 Safari/537.36");

OK! It looks like a command, how or where can I run it to apply it to Freelook?

**Comment by roggenbrot** [comment]
You have to set this in javascript code of `mail-window-controller.js` like in my other pull request:

https://github.com/roggenbrot/freelook/blob/37-notifications/src/controller/mail-window-controller.js

**Comment by sspade1** [comment]
Sorry it is not clear to me.

**Pull request merged**
