### PR TITLE
Add copy / paste / cut / undo / redo / selectAll keyboard shortcuts

### PR DESCRIPTION
**Pull request by michaellatman**
Previously app did not allow you to copy and paste and other standard keyboard shortcuts on Mac. It now does.

### CODE REVIEW

**Comment by eNkru** [comment]
It's good idea to provide those actions in the application menu. However, the PR only make those options appear in the menu. It doesn't do much when you click it. Could you fix this so I could accept the PR.

Also it's better to write a separate controller to handle all application menu logic. It will align the design structure with other codes.

**Comment by michaellatman** [comment]
On Mac they actually function. I’m not really sure what you mean by “click”. Is this right clicking?

Best,

Michael Latman
mlatman@gmail.com

**Comment by michaellatman** [comment]
@eNkru I went ahead and restricted it to Mac and moved to a controller.

**Comment by eNkru** [comment]
> @eNkru I went ahead and restricted it to Mac and moved to a controller.

I am mainly working on Linux environment, so didn't realise the copy / paste etc. are not working in Mac. It looks like a workaround for Mac OS. 

Thanks for the code refactoring. :)

**Comment by michaellatman** [comment]
I think OS X requires the items to be in the menu to enable the functionality for whatever reason.

**Pull request merged**
